extends Node

var set_data:Dictionary = {
	"music": 1,
	"time1": "",
	"time2": "",
	"time3": "",
	"time4": "",
	"time5": "",
	"time6": "",
	"name1": "",
	"name2": "",
	"name3": "",
	"name4": "",
	"name5": "",
	"name6": "",
	"其他存档":{
		
	},
	"剧情跳过": false,
	"Map_num":1,
	"MainMenuBG":1,
	"BackGroundMusic": true,
	"RoleOrMonsterHit": true,
	"MonsterBloodSHow":true,#是否显示血条
	"MonsterBloodTextSHow":false,#是否显示血条文字,
	"MonsterLittleBlood":true,#是否显示小血条
	"MusicFB": 0,#背景
	"MusicFB_2": 0,#音效
	"NoShowMonsterBody": true,
	"HpBarDelay": false,
	"FristGame": true,
	"AutomaticallyPickUpItems": false,
	"PickUpItemsMusic": false,
	"CurrentLevelPage":0,
	"CreateMonsterSpeed": 1.2,
	"Difficult": 0,
	"LevelInfo": false,
	"xg":false,
	"Music4": false,
	"LevelHYS": false,
	"LevelLSH": false,
	"LevelTT": false,
	"MyTime":{},
	"FileValue":1.0,
	"XiaoBaiLong":false,
	"NotShowRoleBody":false,
	"NotShowRoleEQ":false,
	"CdNum":6,
	"MobileControlsLayout": {
		"Joystick": {"x": 0.18, "y": 0.76},
		"Attack": {"x": 0.86, "y": 0.78},
		"Jump": {"x": 0.92, "y": 0.60},
		"Skill1": {"x": 0.70, "y": 0.82},
		"Skill2": {"x": 0.64, "y": 0.69},
		"Skill3": {"x": 0.69, "y": 0.54},
		"Skill4": {"x": 0.78, "y": 0.44},
		"Skill5": {"x": 0.87, "y": 0.40},
		"Magic": {"x": 0.76, "y": 0.16},
		"Wushuang": {"x": 0.84, "y": 0.16},
		"Zhenfa": {"x": 0.92, "y": 0.16},
	},
	"MobileControlsOpacity": 1.0,
	"MobileControlsSafePadding": 28.0,
	"MobileControlsShow": false,
}
